"""
Problem:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""

sum = 0
# create a fibonacci sequence up to 4000000
fibonacci = [1,2]
while fibonacci[-1]<=4000000:
    fibonacci.append(fibonacci[-1]+fibonacci[-2])
#sum all fibonacci numbers up to 400000 that are multiples of 2
for x in fibonacci:
    if x%2==0:
        sum +=x
print sum
    
